---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: couchdb
  template:
    metadata:
      labels:
        name: couchdb
    spec:
      containers:
        - image: couchdb:3.1
          name: couchdb
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              value: password

---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
spec:
  ports:
    - port: 5984
      targetPort: 5984
  selector:
    name: couchdb