---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: process-registered-user
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: anthonyamanse/test-cloudevents:v6
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: process-deleted-user
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: anthonyamanse/test-cloudevents:v6